###
## Styles
#

classes: {
  container: {
    label.near: bottom-left
    icon.near: bottom-right
    style: {
      fill: "#f1f1f1"
      stroke: "#f1f1f1"
      font-size: 14
    }
  }
}

direction: right

###
## Actors
#

app: Customer\nApplication {
  shape: image
  icon: "../_icons/identicons/icon-web-app.png"
}

auth0: Auth0 {
  icon: "../_icons/identicons/icon-auth0-server.png"
  class: container

  login: Login {
    shape: image
    icon: "../_icons/identicons/icon-login.png"
  }

  actions: Actions {
    shape: image
    icon: "../_icons/identicons/icon-pipeline-b.png"
  }
}

service: External service {
  class: container
  icon: "../_icons/identicons/icon-server.png"

  prompt: Prompt {
    shape: image
    icon: "../_icons/identicons/icon-web-app.png"
  }
}

###
## Diagram
#

app -> auth0.login: 1. Login
auth0.login -> auth0.actions: 2. Successful login 
auth0.actions -> service.prompt: 3. Redirect with state
auth0.actions <- service.prompt: 4. Redirect with state
auth0.actions -> app: 5. Callback
