###
## Styles
#

direction: right

###
## Actors
#

machine: Owned machine {
  automate: Automation {
    shape: image
    icon: "../_icons/identicons/icon-bot.png"
  }
  getter: API Getter {
    shape: image
    icon: "../_icons/identicons/icon-cli-script.png"
  }
}

fs: Owned file system {
  store: "" {
    shape: image
    icon: "../_icons/identicons/icon-database.png"
  }
}

ext: External {
  style.fill: "#f1f1f1"
  style.stroke: "#e1e1e1"

  api: API {
    shape: image
    icon: "../_icons/identicons/icon-api.png"
  }
}

machine.automate -> machine.automate: (1) Wait
machine.automate -> machine.getter: (2) Trigger
machine.getter -> fs.store: (3) Read queue
machine.getter -> ext.api: (4) Call API
machine.getter -> machine.getter: (5) Process
machine.getter -> fs.store: (6) Save
machine.getter -> fs.store: (7) Update queue
