###
## Styles
#
vars: {
  image-style: {
    shape: image
    height: 80
    style.font-size: 20
  }
}

classes: {
  container: {
    label.near: bottom-left
    icon.near: bottom-right
    style: {
      fill: "#f1f1f1"
      stroke: "#f1f1f1"
    }
  }
  database: {
    icon: "https://www.joshcanhelp.com/_images/identicons/icon-database.png"
    ...${image-style}
  }
  server: {
    icon: "https://www.joshcanhelp.com/_images/identicons/icon-server.png"
    ...${image-style}
  }
  pipeline: {
    icon: "https://www.joshcanhelp.com/_images/identicons/icon-pipeline-b.png"
    ...${image-style}
  }
  document: {
    icon: "https://www.joshcanhelp.com/_images/identicons/icon-attributes.png"
    ...${image-style}
  }
  spa: {
    icon: "https://www.joshcanhelp.com/_images/identicons/icon-spa.png"
    ...${image-style}
  }
}

direction: right

###
## Actors
#

data-source-1: Data Source {
  class: database
}

data-source-2: Data Source {
  class: database
}

data-source-3: Data Source {
  class: database
}

extractor-1: Extractor {
  class: server
}

extractor-2: Extractor {
  class: server
}

infra: Data Infrastructure {
  class: container
  
  data-lake: Layer 1:\nRaw Data {
    class: database
  }

  transformer: Transform {
    class: pipeline
  }

  data-layer-1: Layer 2:\nProcessed Data {
    class: database
  }

  data-layer-2: Layer 2:\nProcessed Data {
    class: database
  }

  report-1: Report {
    class: document
  }

  report-2: Dashboard {
    class: spa
  }

  report-3: Report {
    class: document
  }

  report-4: Dashboard {
    class: spa
  }
}

###
## Diagram
#

data-source-1<-extractor-1
data-source-2<-extractor-1
data-source-3<-extractor-2
extractor-1->infra.data-lake
extractor-2->infra.data-lake
infra.data-lake<-infra.transformer
infra.transformer->infra.data-layer-1
infra.transformer->infra.data-layer-2
infra.data-layer-1->infra.report-1
infra.data-layer-1->infra.report-2
infra.data-layer-2->infra.report-3
infra.data-layer-2->infra.report-4
